title   : German Academic Web
description: German Academic Web OpenData
url     : https://german-academic-web.de
lang: en
timezone: Europe/Berlin
author:
  type      : organization
  name      : Humboldt-UniversitÃ¤t zu Berlin
  url       : https://www.hu-berlin.de/
  avatar    : # path or url of avatar image
  bio       :
  email     :
  github    : # "user_name" the last part of your profile url, e.g. https://github.com/user_name
  npm       : # "user_name" the last part of your profile url, e.g. https://www.npmjs.com/~user_name
  telegram  : # "user_name" the last part of your profile url, e.g. https://t.me/user_name


## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: user_name/repo_name
repository_tree: master
license: CC-BY-NC-4.0 # "CC-BY-4.0", "CC-BY-SA-4.0", "CC-BY-NC-4.0", "CC-BY-ND-4.0"

## TOC
toc:
  selectors: # "h1,h2,h3" (default)


theme: minima
show_excerpts: true
plugins:
  - jekyll-feed
  - jekyll-sitemap
